object Versions {
    const val GRADLE_ANDROID = "4.0.1"

    const val KOTLIN = "1.4.10"
    const val APPCOMPAT = "1.2.0"
    const val MATERIAL = "1.2.0"
    const val ROOM = "2.3.0-alpha02"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.3.0"
    const val LIFECYCLE = "2.2.0"
    const val CORE_KTX = "1.3.1"
    const val FRAGMENT_KTX = "1.2.5"
    const val CONSTRAIN_LAYOUT = "2.0.1"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val DAGGER = "2.28"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.7.2"
    const val RX_JAVA = "2.2.19"
    const val RX_ANDROID = "2.1.1"
    const val PAGING = "2.1.2"
    const val LINT = "27.0.1"
    const val GLIDE = "4.11.0"

    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.12"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.9.3"
    const val ASSERTJ = "3.14.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.2.2"
}
